[build]
  command = "NEXT_PUBLIC_API_URL=/api npm run build:netlify"
  publish = "frontend/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.api]
  external_node_modules = ["@prisma/client", "@nestjs/microservices"]
  # Incluye los motores de Prisma en el paquete de la función
  included_files = ["backend/node_modules/.prisma/client/*.node"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200


