[build]
  command = "npm run build"
  publish = "frontend/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "backend/dist/src"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/lambda/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = {role = ["!*"]} # Solo si no es una función
